-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    -   id: check-yaml
        exclude: docs/*
    -   id: end-of-file-fixer
        exclude: docs/*
    -   id: check-ast
        language_version: python3.7
        exclude: docs/*
    -   id: trailing-whitespace
        exclude: docs/*
    -   id: requirements-txt-fixer
        exclude: docs/*
-   repo: git://github.com/pre-commit/mirrors-pylint
    rev: v2.1.1
    hooks:
    -   id: pylint
        args:
        - --rcfile=.pylintrc
        python-version: python3.7
        exclude: >
            (?x)^(
                docs/.+|
                punch_version.py|
                punch_config.py|
            )$
-   repo: git://github.com/asottile/reorder_python_imports
    rev: v1.0.1
    hooks:
    -   id: reorder-python-imports
        python-version: python3.7
        exclude: docs/*
-   repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
    rev: v0.3.3
    hooks:
    -   id: pep257
        args:
        - --ignore=D301,D203
        python-version: python3.7
        exclude: >
            (?x)^(
                docs/.+|
                punch_version.py|
                punch_config.py|
            )$
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
      -   id: black
          args: [--line-length=120, --safe]
          python-version: python3.7
          exclude: >
            (?x)^(
                docs/.+|
                punch_version.py|
                punch_config.py
            )$
